### ISSUE TITLE
Problem with building

### ISSUE THREAD

**Issue by Ransqi** [hyperledger/sawtooth-core#2391]
When I ran the script `docker-compose -f docker/compose/sawtooth-build.yaml up`, I got:

    WARNING: The ISOLATION_ID variable is not set. Defaulting to a blank string.
    ERROR: no such image: sawtooth-validator-local:: invalid reference format

How to deal with it?

**Comment by charalarg** [comment]
You can define the ISOLATION_ID variable in your .env file and use the [“--env-file”](https://docs.docker.com/compose/environment-variables/#using-the---env-file--option) option in order to pass the config in your docker-compose images. You can also use [this](https://github.com/hyperledger/sawtooth-core/blob/main/.env) .env file.
